#!/bin/bash

set -e

./usage 2 "saws instance list-by-tag <tag-name> <tag-value>" "$@"

tag_name=$1
tag_value=$2

aws ec2 describe-instances \
	--filters \
		"Name=tag:$tag_name,Values=$tag_value" \
	--output text \
	--query "Reservations[].Instances[?State.Name!='terminated'].InstanceId" | tr '\t' '\n'

