#!/bin/bash

set -e

./usage 2 "saws subnet get-by-tag <tag-name> <tag-value>" "$@"

tag_name=$1
tag_value=$2

aws ec2 describe-subnets \
	--filters \
		"Name=tag:$tag_name,Values=$tag_value" \
	--output text \
	--query "Subnets[].SubnetId" | tr '\t' '\n'
