#!/bin/bash

set -e

./usage 2 "saws internet-gateway detach <internet-gateway-id> <vpc-id>" "$@"

internet_gateway_id=$1
vpc_id=$2

aws ec2 detach-internet-gateway \
	--internet-gateway-id $internet_gateway_id \
	--vpc-id $vpc_id

